# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        CryptoPriceItem,
        CryptoPricesResponse,
        ErrorResponse,
        MarketsListResponse,
        PaginationBlock,
        PlatformMarket,
        PlatformMarketPlatform,
        SportsMatchingResponse,
        UnifiedMarket,
        UnifiedMarketProvider,
    )
    from .errors import (
        BadGatewayError,
        BadRequestError,
        ForbiddenError,
        InternalServerError,
        ServiceUnavailableError,
        TooManyRequestsError,
        UnauthorizedError,
    )
    from ._default_clients import DefaultAioHttpClient, DefaultAsyncHttpxClient
    from .client import AsyncPredictorSDK, PredictorSDK
    from .environment import PredictorSDKEnvironment
_dynamic_imports: typing.Dict[str, str] = {
    "AsyncPredictorSDK": ".client",
    "BadGatewayError": ".errors",
    "BadRequestError": ".errors",
    "CryptoPriceItem": ".types",
    "CryptoPricesResponse": ".types",
    "DefaultAioHttpClient": "._default_clients",
    "DefaultAsyncHttpxClient": "._default_clients",
    "ErrorResponse": ".types",
    "ForbiddenError": ".errors",
    "InternalServerError": ".errors",
    "MarketsListResponse": ".types",
    "PaginationBlock": ".types",
    "PlatformMarket": ".types",
    "PlatformMarketPlatform": ".types",
    "PredictorSDK": ".client",
    "PredictorSDKEnvironment": ".environment",
    "ServiceUnavailableError": ".errors",
    "SportsMatchingResponse": ".types",
    "TooManyRequestsError": ".errors",
    "UnauthorizedError": ".errors",
    "UnifiedMarket": ".types",
    "UnifiedMarketProvider": ".types",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AsyncPredictorSDK",
    "BadGatewayError",
    "BadRequestError",
    "CryptoPriceItem",
    "CryptoPricesResponse",
    "DefaultAioHttpClient",
    "DefaultAsyncHttpxClient",
    "ErrorResponse",
    "ForbiddenError",
    "InternalServerError",
    "MarketsListResponse",
    "PaginationBlock",
    "PlatformMarket",
    "PlatformMarketPlatform",
    "PredictorSDK",
    "PredictorSDKEnvironment",
    "ServiceUnavailableError",
    "SportsMatchingResponse",
    "TooManyRequestsError",
    "UnauthorizedError",
    "UnifiedMarket",
    "UnifiedMarketProvider",
]
