# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        CanonicalSportsEvent,
        CanonicalSportsOutcome,
        CanonicalSportsParticipant,
        CanonicalSportsRules,
        CanonicalSportsSourceMarket,
        CanonicalSportsSourceMarketProvider,
        CanonicalSportsSourceOutcome,
        CanonicalSportsSubject,
        CanonicalSportsSubmarket,
        CategoriesResponse,
        CategoryInfo,
        CryptoPriceItem,
        CryptoPricesResponse,
        ErrorResponse,
        EventFanout,
        EventMarket,
        EventResponse,
        EventResponsePlatform,
        GetEventRequestPlatform,
        GetMarketRequestPlatform,
        MarketCategory,
        MarketDetailOutcome,
        MarketDetailPricing,
        MarketDetailPricingAvailability,
        MarketDetailPricingScale,
        MarketDetailPricingSource,
        MarketDetailResponse,
        MarketDetailResponseProvider,
        MarketDetailResponseStatus,
        MarketsListResponse,
        PaginationBlock,
        PaymentRequiredErrorAction,
        PaymentRequiredErrorBody,
        Plan,
        PlansResponse,
        PlatformMarket,
        PlatformMarketPlatform,
        PolymarketPosition,
        PolymarketPositionsResponse,
        PolymarketWalletResponse,
        SportsMatchingResponse,
        UnifiedMarket,
        UnifiedMarketProvider,
    )
    from .errors import (
        BadGatewayError,
        BadRequestError,
        ForbiddenError,
        NotFoundError,
        PaymentRequiredError,
        ServiceUnavailableError,
        TooManyRequestsError,
        UnauthorizedError,
    )
    from ._default_clients import DefaultAioHttpClient, DefaultAsyncHttpxClient
    from .client import AsyncPredictorSDK, PredictorSDK
    from .environment import PredictorSDKEnvironment
_dynamic_imports: typing.Dict[str, str] = {
    "AsyncPredictorSDK": ".client",
    "BadGatewayError": ".errors",
    "BadRequestError": ".errors",
    "CanonicalSportsEvent": ".types",
    "CanonicalSportsOutcome": ".types",
    "CanonicalSportsParticipant": ".types",
    "CanonicalSportsRules": ".types",
    "CanonicalSportsSourceMarket": ".types",
    "CanonicalSportsSourceMarketProvider": ".types",
    "CanonicalSportsSourceOutcome": ".types",
    "CanonicalSportsSubject": ".types",
    "CanonicalSportsSubmarket": ".types",
    "CategoriesResponse": ".types",
    "CategoryInfo": ".types",
    "CryptoPriceItem": ".types",
    "CryptoPricesResponse": ".types",
    "DefaultAioHttpClient": "._default_clients",
    "DefaultAsyncHttpxClient": "._default_clients",
    "ErrorResponse": ".types",
    "EventFanout": ".types",
    "EventMarket": ".types",
    "EventResponse": ".types",
    "EventResponsePlatform": ".types",
    "ForbiddenError": ".errors",
    "GetEventRequestPlatform": ".types",
    "GetMarketRequestPlatform": ".types",
    "MarketCategory": ".types",
    "MarketDetailOutcome": ".types",
    "MarketDetailPricing": ".types",
    "MarketDetailPricingAvailability": ".types",
    "MarketDetailPricingScale": ".types",
    "MarketDetailPricingSource": ".types",
    "MarketDetailResponse": ".types",
    "MarketDetailResponseProvider": ".types",
    "MarketDetailResponseStatus": ".types",
    "MarketsListResponse": ".types",
    "NotFoundError": ".errors",
    "PaginationBlock": ".types",
    "PaymentRequiredError": ".errors",
    "PaymentRequiredErrorAction": ".types",
    "PaymentRequiredErrorBody": ".types",
    "Plan": ".types",
    "PlansResponse": ".types",
    "PlatformMarket": ".types",
    "PlatformMarketPlatform": ".types",
    "PolymarketPosition": ".types",
    "PolymarketPositionsResponse": ".types",
    "PolymarketWalletResponse": ".types",
    "PredictorSDK": ".client",
    "PredictorSDKEnvironment": ".environment",
    "ServiceUnavailableError": ".errors",
    "SportsMatchingResponse": ".types",
    "TooManyRequestsError": ".errors",
    "UnauthorizedError": ".errors",
    "UnifiedMarket": ".types",
    "UnifiedMarketProvider": ".types",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AsyncPredictorSDK",
    "BadGatewayError",
    "BadRequestError",
    "CanonicalSportsEvent",
    "CanonicalSportsOutcome",
    "CanonicalSportsParticipant",
    "CanonicalSportsRules",
    "CanonicalSportsSourceMarket",
    "CanonicalSportsSourceMarketProvider",
    "CanonicalSportsSourceOutcome",
    "CanonicalSportsSubject",
    "CanonicalSportsSubmarket",
    "CategoriesResponse",
    "CategoryInfo",
    "CryptoPriceItem",
    "CryptoPricesResponse",
    "DefaultAioHttpClient",
    "DefaultAsyncHttpxClient",
    "ErrorResponse",
    "EventFanout",
    "EventMarket",
    "EventResponse",
    "EventResponsePlatform",
    "ForbiddenError",
    "GetEventRequestPlatform",
    "GetMarketRequestPlatform",
    "MarketCategory",
    "MarketDetailOutcome",
    "MarketDetailPricing",
    "MarketDetailPricingAvailability",
    "MarketDetailPricingScale",
    "MarketDetailPricingSource",
    "MarketDetailResponse",
    "MarketDetailResponseProvider",
    "MarketDetailResponseStatus",
    "MarketsListResponse",
    "NotFoundError",
    "PaginationBlock",
    "PaymentRequiredError",
    "PaymentRequiredErrorAction",
    "PaymentRequiredErrorBody",
    "Plan",
    "PlansResponse",
    "PlatformMarket",
    "PlatformMarketPlatform",
    "PolymarketPosition",
    "PolymarketPositionsResponse",
    "PolymarketWalletResponse",
    "PredictorSDK",
    "PredictorSDKEnvironment",
    "ServiceUnavailableError",
    "SportsMatchingResponse",
    "TooManyRequestsError",
    "UnauthorizedError",
    "UnifiedMarket",
    "UnifiedMarketProvider",
]
