# This file was auto-generated by Fern from our API Definition.

import typing

import httpx
from .core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .core.logging import LogConfig, Logger
from .core.request_options import RequestOptions
from .environment import PredictorSDKEnvironment
from .raw_client import AsyncRawPredictorSDK, RawPredictorSDK
from .types.crypto_prices_response import CryptoPricesResponse
from .types.event_response import EventResponse
from .types.get_event_request_platform import GetEventRequestPlatform
from .types.get_market_request_platform import GetMarketRequestPlatform
from .types.market_detail_response import MarketDetailResponse
from .types.markets_list_response import MarketsListResponse
from .types.polymarket_positions_response import PolymarketPositionsResponse
from .types.polymarket_wallet_response import PolymarketWalletResponse
from .types.sports_matching_response import SportsMatchingResponse


class PredictorSDK:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : PredictorSDKEnvironment
        The environment to use for requests from the client. from .environment import PredictorSDKEnvironment



        Defaults to PredictorSDKEnvironment.PRODUCTION



    token : typing.Union[str, typing.Callable[[], str]]
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.Client]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    Examples
    --------
    from predictorsdk import PredictorSDK

    client = PredictorSDK(
        token="YOUR_TOKEN",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: PredictorSDKEnvironment = PredictorSDKEnvironment.PRODUCTION,
        token: typing.Union[str, typing.Callable[[], str]],
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.Client] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        )
        self._client_wrapper = SyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            token=token,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.Client(timeout=_defaulted_timeout, follow_redirects=follow_redirects)
            if follow_redirects is not None
            else httpx.Client(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
            logging=logging,
        )
        self._raw_client = RawPredictorSDK(client_wrapper=self._client_wrapper)

    @property
    def with_raw_response(self) -> RawPredictorSDK:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPredictorSDK
        """
        return self._raw_client

    def get_sports_matching_markets(
        self,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        include_settled: typing.Optional[bool] = None,
        kalshi_event_ticker: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        polymarket_market_slug: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        predict_market_id: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        sxbet_market_id: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SportsMatchingResponse:
        """
        Find cross-platform market matches for sports events. When called without parameters, returns all currently matched sports markets with cursor-based pagination (default `limit=25`, max `100`). Provide a Kalshi event ticker, Polymarket slug, Predict market ID, or SX Bet market ID to look up a specific event — lookups return the full match immediately and skip pagination.

        Parameters
        ----------
        limit : typing.Optional[int]
            Maximum number of matched events to return per page. Range 1–100, default 25. Ignored when a platform-ID filter is supplied.

        cursor : typing.Optional[str]
            Opaque cursor from a previous response's `pagination.nextCursor` in the SDKs (raw JSON: `pagination.next_cursor`). Must be used with the same filter set — a cursor from `include_settled=true` cannot be replayed against `include_settled=false` and will return `400`.

        include_settled : typing.Optional[bool]
            When `true`, include settled/archived events alongside currently live matches. Defaults to `false`.

        kalshi_event_ticker : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Kalshi event ticker(s) to find matching markets for (e.g. `KXNFLGAME-25AUG16ARIDEN`). Provide the parameter multiple times for multiple tickers. Only one filter type may be used per request. Lookup mode — pagination parameters are ignored.

        polymarket_market_slug : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Polymarket market slug(s) to find matching markets for (e.g. `nfl-ari-den-2025-08-16`). Provide the parameter multiple times for multiple slugs. Only one filter type may be used per request. Lookup mode — pagination parameters are ignored.

        predict_market_id : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Predict market ID(s) to find matching markets for (e.g. `110629`). Provide the parameter multiple times for multiple IDs. Only one filter type may be used per request. Lookup mode — pagination parameters are ignored.

        sxbet_market_id : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            SX Bet market ID(s) to find matching markets for (e.g. `0x4c000abdbf197ef32ecdf15561b1d636f1e5b02629f466678757fd83e2ec3599`). Provide the parameter multiple times for multiple IDs. Only one filter type may be used per request. Lookup mode — pagination parameters are ignored.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SportsMatchingResponse
            Matching markets keyed by identifier

        Examples
        --------
        from predictorsdk import PredictorSDK

        client = PredictorSDK(
            token="YOUR_TOKEN",
        )
        client.get_sports_matching_markets()
        """
        _response = self._raw_client.get_sports_matching_markets(
            limit=limit,
            cursor=cursor,
            include_settled=include_settled,
            kalshi_event_ticker=kalshi_event_ticker,
            polymarket_market_slug=polymarket_market_slug,
            predict_market_id=predict_market_id,
            sxbet_market_id=sxbet_market_id,
            request_options=request_options,
        )
        return _response.data

    def get_markets(
        self,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MarketsListResponse:
        """
        Returns a paginated list of unified markets from all supported prediction market providers. Uses cursor-based pagination with default `limit=25`, max `100`.

        Parameters
        ----------
        limit : typing.Optional[int]
            Maximum number of markets to return per page. Range 1–100, default 25.

        cursor : typing.Optional[str]
            Opaque cursor from a previous response's `pagination.nextCursor` in the SDKs (raw JSON: `pagination.next_cursor`).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MarketsListResponse
            Paginated list of markets

        Examples
        --------
        from predictorsdk import PredictorSDK

        client = PredictorSDK(
            token="YOUR_TOKEN",
        )
        client.get_markets()
        """
        _response = self._raw_client.get_markets(limit=limit, cursor=cursor, request_options=request_options)
        return _response.data

    def get_market(
        self,
        market_id: str,
        *,
        platform: typing.Optional[GetMarketRequestPlatform] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MarketDetailResponse:
        """
        Returns a single market across the four supported platforms. The `market_id` is either the composite form returned by `GET /v1/markets` (`{provider}:{native_id}`, e.g. `kalshi:KXNBA-26-SAS`) or the platform-native identifier. Composite IDs dispatch unambiguously by prefix. Native IDs are routed by format inference: Kalshi tickers match the all-caps-with-hyphens shape (`KX…-…`); SX Bet hashes match `0x` + 64 hex characters; numeric ids and kebab-case slugs are shared shape between Polymarket and Predict and probe Polymarket first, falling back to Predict on 404. Pass `?platform=` explicitly to skip the probe.

        Identity fields (id/provider/provider_id/title/status/ outcomes[].name) are strict-universal: every platform's single-market endpoint exposes them natively without a second fetch. close timestamps and parent event ids remain omitted (not nullable) — Predict's close time lives on the parent category and Polymarket's market record carries no event id.

        The pricing tier adds per-outcome quotes (`price`/`bid`/`ask`/ `last` as 0–1 probability numbers — price IS the implied probability), a `pricing` envelope (`availability`/`scale`/ `source`/`as_of`/`neg_risk`), and market-level aggregates (`liquidity_usd`, `volume_24h_usd`, `volume_total_usd`, plus Kalshi contract-count mirrors and `open_interest`). Kalshi/ Polymarket/Predict quotes come from the same record the identity fetch returns (`pricing.source=market_record`). SX Bet's market record carries no pricing, so the server makes one bounded second fetch to its best-odds order-book endpoint (`pricing.source=orderbook`) and on timeout/error degrades to `pricing.availability=unavailable` with identity intact — pricing failures never fail the lookup. Aggregates a platform doesn't natively expose are explicit `null` (e.g. Kalshi reports volume in contracts, so `volume_*_usd` stays null rather than fabricating a USD figure; its upstream `liquidity_dollars` field is deprecated and always zero, so `liquidity_usd` is null too).

        Parameters
        ----------
        market_id : str
            Composite (`{provider}:{native_id}`) or platform-native market identifier. Examples per platform: Kalshi market ticker (`KXNBA-26-SAS`), Polymarket numeric id or slug (`540817` or `new-rhianna-album-before-gta-vi-926`), Predict market id (`356635`), SX Bet `marketHash` (`0x…64hex`).

        platform : typing.Optional[GetMarketRequestPlatform]
            Optional platform override. When omitted, inferred from the composite prefix or from the native ID format (`KX…` → Kalshi, `0x…64hex` → SX Bet). Numeric IDs and kebab-case slugs are shared shape between Polymarket and Predict; in that case the service probes Polymarket first and falls back to Predict on 404. Pass `platform` explicitly to skip the probe. When the override contradicts a composite prefix (e.g. `kalshi:X` with `?platform=polymarket`), the request returns 400.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MarketDetailResponse
            Market detail

        Examples
        --------
        from predictorsdk import PredictorSDK

        client = PredictorSDK(
            token="YOUR_TOKEN",
        )
        client.get_market(
            market_id="kalshi:KXNBA-26-SAS",
        )
        """
        _response = self._raw_client.get_market(market_id, platform=platform, request_options=request_options)
        return _response.data

    def get_binance_crypto_prices(
        self,
        *,
        currency: str,
        start_time: typing.Optional[int] = None,
        end_time: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        pagination_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CryptoPricesResponse:
        """
        Returns per-second price data for a Binance trading pair. When called without a time range, returns the latest price. With `start_time` and `end_time`, returns historical per-second prices in newest-first order. Supports cursor-based pagination for large result sets. Unknown or invalid symbols return `200` with `{"prices":[]}` and omit `total`.

        Parameters
        ----------
        currency : str
            Binance trading pair (e.g. `btcusdt`, `ethusdt`, `solusdt`). Must contain only alphanumeric characters (no hyphens, underscores, or other separators). Uppercase is accepted and automatically lowercased (e.g. `BTCUSDT` → `btcusdt`). Must be a valid Binance symbol; unknown symbols return `200` with an empty `prices` array.

        start_time : typing.Optional[int]
            Start of the time range as a Unix timestamp in milliseconds (inclusive). Negative values are clamped to 0.

        end_time : typing.Optional[int]
            End of the time range as a Unix timestamp in milliseconds (inclusive). Negative values are clamped to 0.

        limit : typing.Optional[int]
            Maximum number of prices to return. Defaults to 100 when a time range is present. Values above 100 are silently clamped to 100. Without a time range, this parameter is ignored — the endpoint always returns the single latest price.

        pagination_key : typing.Optional[str]
            Base64-encoded cursor from a previous response to fetch the next page of results.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CryptoPricesResponse
            Crypto price data

        Examples
        --------
        from predictorsdk import PredictorSDK

        client = PredictorSDK(
            token="YOUR_TOKEN",
        )
        client.get_binance_crypto_prices(
            currency="btcusdt",
        )
        """
        _response = self._raw_client.get_binance_crypto_prices(
            currency=currency,
            start_time=start_time,
            end_time=end_time,
            limit=limit,
            pagination_key=pagination_key,
            request_options=request_options,
        )
        return _response.data

    def get_polymarket_wallet(
        self,
        *,
        address: typing.Optional[str] = None,
        username: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PolymarketWalletResponse:
        """
        Returns the public profile (image and display name) for a Polymarket wallet. Accepts either a wallet `address` (proxy or signer EOA) or a Polymarket `username`. Exactly one of the two must be supplied — passing both returns `400`.

        When `address` is the underlying signer EOA, the endpoint resolves it to the deterministic proxy address and returns the proxy's profile, with `signer` echoing the input.

        When `username` is supplied, the endpoint resolves it to the wallet via Polymarket's profile search. Match is case-insensitive and exact: a query of `Theo` resolves the user literally named `theo` but does not resolve `theo46` or `Theo47`. A leading `@` is accepted (and stripped) as a convenience for callers used to Twitter-style handles. `signer` is always `null` on the username path. Profiles that don't exist (or only match fuzzily) return `404`.

        Parameters
        ----------
        address : typing.Optional[str]
            Wallet address to look up. May be a Polymarket proxy address or the underlying signer EOA — the endpoint resolves either form. Must match `^0x[a-fA-F0-9]{40}$`. Mixed-case input is accepted and lowercased in the response. Mutually exclusive with `username`; exactly one of the two is required.

        username : typing.Optional[str]
            Polymarket display name to look up. Match is case-insensitive and exact against the user's stored `name` (so `Car`, `car`, and `CAR` all resolve, but `Theo` does not match `Theo47`). A leading `@` is accepted and stripped before the lookup. Mutually exclusive with `address`; exactly one of the two is required. Example: `Car`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PolymarketWalletResponse
            Public profile for the wallet

        Examples
        --------
        from predictorsdk import PredictorSDK

        client = PredictorSDK(
            token="YOUR_TOKEN",
        )
        client.get_polymarket_wallet(
            address="0x7c3db723f1d4d8cb9c550095203b686cb11e5c6b",
        )
        """
        _response = self._raw_client.get_polymarket_wallet(
            address=address, username=username, request_options=request_options
        )
        return _response.data

    def list_polymarket_wallet_positions(
        self,
        *,
        address: typing.Optional[str] = None,
        username: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PolymarketPositionsResponse:
        """
        Returns the current Polymarket positions for a wallet. Accepts either a wallet `address` (proxy address only — see note below) or a Polymarket `username`. Exactly one of the two must be supplied — passing both returns `400`.

        v1 surfaces a minimal field set so the endpoint scaffolding can be verified end-to-end: `condition_id` (which market), `outcome` (which side), and `shares` (how much). Title/slug, avg/current price, PnL (`cash_pnl`, `realized_pnl`), `redeemable`/`mergeable` flags, and event metadata will be added in follow-ups.

        `total` in the pagination block is always `0` because the upstream Data API does not return a total count; rely on `has_more` + `next_cursor` to paginate.

        **EOA inputs are not auto-resolved on this endpoint.** Unlike `/v1/polymarket/wallet`, this endpoint does not perform the EOA→proxy CREATE2 resolution. Callers with a signer EOA should call `/v1/polymarket/wallet` first to resolve the proxy, then pass the returned `address`. Passing an EOA directly will return an empty `data` array.

        Parameters
        ----------
        address : typing.Optional[str]
            Polymarket proxy wallet address. Must match `^0x[a-fA-F0-9]{40}$`. Mixed-case input is accepted and lowercased in the response. Mutually exclusive with `username`; exactly one of the two is required.

        username : typing.Optional[str]
            Polymarket display name to resolve to a proxy wallet. Match is case-insensitive and exact against the user's stored `name`. A leading `@` is accepted and stripped. Mutually exclusive with `address`.

        limit : typing.Optional[int]
            Number of items per page. Defaults to 50.

        cursor : typing.Optional[str]
            Opaque cursor from a previous response's `pagination.next_cursor`. Bound to the resolved wallet address — replaying a cursor against a different identifier returns `400`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PolymarketPositionsResponse
            Wallet positions

        Examples
        --------
        from predictorsdk import PredictorSDK

        client = PredictorSDK(
            token="YOUR_TOKEN",
        )
        client.list_polymarket_wallet_positions(
            address="0x7c3db723f1d4d8cb9c550095203b686cb11e5c6b",
        )
        """
        _response = self._raw_client.list_polymarket_wallet_positions(
            address=address, username=username, limit=limit, cursor=cursor, request_options=request_options
        )
        return _response.data

    def get_event(
        self,
        event_id: str,
        *,
        platform: typing.Optional[GetEventRequestPlatform] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EventResponse:
        """
        Returns a single event and the markets nested under it on the identified platform. The `event_id` is the platform's native identifier — a Kalshi `event_ticker`, a Polymarket event slug, an SX Bet `eventId`, or a Predict market identifier. The `platform` is inferred from the ID format when unambiguous (`KX…` → Kalshi, `L\\d+` → SX Bet). Numeric IDs and kebab-case slugs are shared shape between Polymarket and Predict; if `?platform=` is omitted in that case, the service probes Polymarket first and falls back to Predict when Polymarket returns 404. Pass `?platform=` explicitly to skip the probe.

        Response is minimal in v0: each market is returned with its platform-native `market_id` and a human-readable `title`. Pricing, volume, status, and timestamps are intentionally deferred — they'll be added as additive fields to `EventMarket` in a later release. The endpoint mirrors the `/v1/markets` rollout pattern (titles first, fields later).

        **Kalshi sibling fanout.** A single Kalshi sports game lives across multiple event tickers that share a game suffix — e.g. `KXMLBGAME-26MAY221840CLEPHI` holds the moneyline, `KXMLBF5TOTAL-26MAY221840CLEPHI` holds the totals, and so on. When the supplied event_ticker belongs to a sport in the sibling registry (MLB, NBA, NFL, NHL, WNBA today), this endpoint fans out across known sibling series in parallel and merges their markets into one response. Siblings that don't exist for a particular game silently drop. Siblings that error are reported under `fanout.siblings_missing`; the primary event still returns 200 in that case. Only the primary fetch failing produces a 4xx/5xx — partial fanouts never fail the request.

        **Polymarket** events already nest the moneyline plus all spread/totals/game-level prop markets under a single event slug, so no fanout is performed. **SX Bet** fixtures similarly bundle game lines per `eventId`. **Predict** currently treats `event_id` as a market identifier and wraps the single market as a 1-element event response, since the upstream `event` concept on Predict is closer to a category than to a multi-market container.

        Parameters
        ----------
        event_id : str
            Platform-native event identifier. Examples per platform: Kalshi event ticker (`KXMLBGAME-26MAY221840CLEPHI`), Polymarket event slug (`mlb-cle-phi-2026-05-22`), SX Bet event id (`L10073358`), Predict market id (`110629`).

        platform : typing.Optional[GetEventRequestPlatform]
            Optional platform override. When omitted, inferred from the `event_id` format: `KX…` → Kalshi, `L\\d+` → SX Bet. Numeric IDs and kebab-case slugs are shared shape between Polymarket and Predict; in that case the service probes Polymarket first and falls back to Predict on 404. Pass `platform` explicitly to skip the probe.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EventResponse
            Event with nested markets

        Examples
        --------
        from predictorsdk import PredictorSDK

        client = PredictorSDK(
            token="YOUR_TOKEN",
        )
        client.get_event(
            event_id="KXMLBGAME-26MAY221840CLEPHI",
        )
        """
        _response = self._raw_client.get_event(event_id, platform=platform, request_options=request_options)
        return _response.data


def _make_default_async_client(
    timeout: typing.Optional[float],
    follow_redirects: typing.Optional[bool],
) -> httpx.AsyncClient:
    try:
        import httpx_aiohttp  # type: ignore[import-not-found]
    except ImportError:
        pass
    else:
        if follow_redirects is not None:
            return httpx_aiohttp.HttpxAiohttpClient(timeout=timeout, follow_redirects=follow_redirects)
        return httpx_aiohttp.HttpxAiohttpClient(timeout=timeout)

    if follow_redirects is not None:
        return httpx.AsyncClient(timeout=timeout, follow_redirects=follow_redirects)
    return httpx.AsyncClient(timeout=timeout)


class AsyncPredictorSDK:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : PredictorSDKEnvironment
        The environment to use for requests from the client. from .environment import PredictorSDKEnvironment



        Defaults to PredictorSDKEnvironment.PRODUCTION



    token : typing.Union[str, typing.Callable[[], str]]
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    async_token : typing.Optional[typing.Callable[[], typing.Awaitable[str]]]
        An async callable that returns a bearer token. Use this when token acquisition involves async I/O (e.g., refreshing tokens via an async HTTP client). When provided, this is used instead of the synchronous token for async requests.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.AsyncClient]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    Examples
    --------
    from predictorsdk import AsyncPredictorSDK

    client = AsyncPredictorSDK(
        token="YOUR_TOKEN",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: PredictorSDKEnvironment = PredictorSDKEnvironment.PRODUCTION,
        token: typing.Union[str, typing.Callable[[], str]],
        headers: typing.Optional[typing.Dict[str, str]] = None,
        async_token: typing.Optional[typing.Callable[[], typing.Awaitable[str]]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.AsyncClient] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        )
        self._client_wrapper = AsyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            token=token,
            headers=headers,
            async_token=async_token,
            httpx_client=httpx_client
            if httpx_client is not None
            else _make_default_async_client(timeout=_defaulted_timeout, follow_redirects=follow_redirects),
            timeout=_defaulted_timeout,
            logging=logging,
        )
        self._raw_client = AsyncRawPredictorSDK(client_wrapper=self._client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPredictorSDK:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPredictorSDK
        """
        return self._raw_client

    async def get_sports_matching_markets(
        self,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        include_settled: typing.Optional[bool] = None,
        kalshi_event_ticker: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        polymarket_market_slug: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        predict_market_id: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        sxbet_market_id: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SportsMatchingResponse:
        """
        Find cross-platform market matches for sports events. When called without parameters, returns all currently matched sports markets with cursor-based pagination (default `limit=25`, max `100`). Provide a Kalshi event ticker, Polymarket slug, Predict market ID, or SX Bet market ID to look up a specific event — lookups return the full match immediately and skip pagination.

        Parameters
        ----------
        limit : typing.Optional[int]
            Maximum number of matched events to return per page. Range 1–100, default 25. Ignored when a platform-ID filter is supplied.

        cursor : typing.Optional[str]
            Opaque cursor from a previous response's `pagination.nextCursor` in the SDKs (raw JSON: `pagination.next_cursor`). Must be used with the same filter set — a cursor from `include_settled=true` cannot be replayed against `include_settled=false` and will return `400`.

        include_settled : typing.Optional[bool]
            When `true`, include settled/archived events alongside currently live matches. Defaults to `false`.

        kalshi_event_ticker : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Kalshi event ticker(s) to find matching markets for (e.g. `KXNFLGAME-25AUG16ARIDEN`). Provide the parameter multiple times for multiple tickers. Only one filter type may be used per request. Lookup mode — pagination parameters are ignored.

        polymarket_market_slug : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Polymarket market slug(s) to find matching markets for (e.g. `nfl-ari-den-2025-08-16`). Provide the parameter multiple times for multiple slugs. Only one filter type may be used per request. Lookup mode — pagination parameters are ignored.

        predict_market_id : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Predict market ID(s) to find matching markets for (e.g. `110629`). Provide the parameter multiple times for multiple IDs. Only one filter type may be used per request. Lookup mode — pagination parameters are ignored.

        sxbet_market_id : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            SX Bet market ID(s) to find matching markets for (e.g. `0x4c000abdbf197ef32ecdf15561b1d636f1e5b02629f466678757fd83e2ec3599`). Provide the parameter multiple times for multiple IDs. Only one filter type may be used per request. Lookup mode — pagination parameters are ignored.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SportsMatchingResponse
            Matching markets keyed by identifier

        Examples
        --------
        import asyncio

        from predictorsdk import AsyncPredictorSDK

        client = AsyncPredictorSDK(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.get_sports_matching_markets()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_sports_matching_markets(
            limit=limit,
            cursor=cursor,
            include_settled=include_settled,
            kalshi_event_ticker=kalshi_event_ticker,
            polymarket_market_slug=polymarket_market_slug,
            predict_market_id=predict_market_id,
            sxbet_market_id=sxbet_market_id,
            request_options=request_options,
        )
        return _response.data

    async def get_markets(
        self,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MarketsListResponse:
        """
        Returns a paginated list of unified markets from all supported prediction market providers. Uses cursor-based pagination with default `limit=25`, max `100`.

        Parameters
        ----------
        limit : typing.Optional[int]
            Maximum number of markets to return per page. Range 1–100, default 25.

        cursor : typing.Optional[str]
            Opaque cursor from a previous response's `pagination.nextCursor` in the SDKs (raw JSON: `pagination.next_cursor`).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MarketsListResponse
            Paginated list of markets

        Examples
        --------
        import asyncio

        from predictorsdk import AsyncPredictorSDK

        client = AsyncPredictorSDK(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.get_markets()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_markets(limit=limit, cursor=cursor, request_options=request_options)
        return _response.data

    async def get_market(
        self,
        market_id: str,
        *,
        platform: typing.Optional[GetMarketRequestPlatform] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MarketDetailResponse:
        """
        Returns a single market across the four supported platforms. The `market_id` is either the composite form returned by `GET /v1/markets` (`{provider}:{native_id}`, e.g. `kalshi:KXNBA-26-SAS`) or the platform-native identifier. Composite IDs dispatch unambiguously by prefix. Native IDs are routed by format inference: Kalshi tickers match the all-caps-with-hyphens shape (`KX…-…`); SX Bet hashes match `0x` + 64 hex characters; numeric ids and kebab-case slugs are shared shape between Polymarket and Predict and probe Polymarket first, falling back to Predict on 404. Pass `?platform=` explicitly to skip the probe.

        Identity fields (id/provider/provider_id/title/status/ outcomes[].name) are strict-universal: every platform's single-market endpoint exposes them natively without a second fetch. close timestamps and parent event ids remain omitted (not nullable) — Predict's close time lives on the parent category and Polymarket's market record carries no event id.

        The pricing tier adds per-outcome quotes (`price`/`bid`/`ask`/ `last` as 0–1 probability numbers — price IS the implied probability), a `pricing` envelope (`availability`/`scale`/ `source`/`as_of`/`neg_risk`), and market-level aggregates (`liquidity_usd`, `volume_24h_usd`, `volume_total_usd`, plus Kalshi contract-count mirrors and `open_interest`). Kalshi/ Polymarket/Predict quotes come from the same record the identity fetch returns (`pricing.source=market_record`). SX Bet's market record carries no pricing, so the server makes one bounded second fetch to its best-odds order-book endpoint (`pricing.source=orderbook`) and on timeout/error degrades to `pricing.availability=unavailable` with identity intact — pricing failures never fail the lookup. Aggregates a platform doesn't natively expose are explicit `null` (e.g. Kalshi reports volume in contracts, so `volume_*_usd` stays null rather than fabricating a USD figure; its upstream `liquidity_dollars` field is deprecated and always zero, so `liquidity_usd` is null too).

        Parameters
        ----------
        market_id : str
            Composite (`{provider}:{native_id}`) or platform-native market identifier. Examples per platform: Kalshi market ticker (`KXNBA-26-SAS`), Polymarket numeric id or slug (`540817` or `new-rhianna-album-before-gta-vi-926`), Predict market id (`356635`), SX Bet `marketHash` (`0x…64hex`).

        platform : typing.Optional[GetMarketRequestPlatform]
            Optional platform override. When omitted, inferred from the composite prefix or from the native ID format (`KX…` → Kalshi, `0x…64hex` → SX Bet). Numeric IDs and kebab-case slugs are shared shape between Polymarket and Predict; in that case the service probes Polymarket first and falls back to Predict on 404. Pass `platform` explicitly to skip the probe. When the override contradicts a composite prefix (e.g. `kalshi:X` with `?platform=polymarket`), the request returns 400.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MarketDetailResponse
            Market detail

        Examples
        --------
        import asyncio

        from predictorsdk import AsyncPredictorSDK

        client = AsyncPredictorSDK(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.get_market(
                market_id="kalshi:KXNBA-26-SAS",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_market(market_id, platform=platform, request_options=request_options)
        return _response.data

    async def get_binance_crypto_prices(
        self,
        *,
        currency: str,
        start_time: typing.Optional[int] = None,
        end_time: typing.Optional[int] = None,
        limit: typing.Optional[int] = None,
        pagination_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CryptoPricesResponse:
        """
        Returns per-second price data for a Binance trading pair. When called without a time range, returns the latest price. With `start_time` and `end_time`, returns historical per-second prices in newest-first order. Supports cursor-based pagination for large result sets. Unknown or invalid symbols return `200` with `{"prices":[]}` and omit `total`.

        Parameters
        ----------
        currency : str
            Binance trading pair (e.g. `btcusdt`, `ethusdt`, `solusdt`). Must contain only alphanumeric characters (no hyphens, underscores, or other separators). Uppercase is accepted and automatically lowercased (e.g. `BTCUSDT` → `btcusdt`). Must be a valid Binance symbol; unknown symbols return `200` with an empty `prices` array.

        start_time : typing.Optional[int]
            Start of the time range as a Unix timestamp in milliseconds (inclusive). Negative values are clamped to 0.

        end_time : typing.Optional[int]
            End of the time range as a Unix timestamp in milliseconds (inclusive). Negative values are clamped to 0.

        limit : typing.Optional[int]
            Maximum number of prices to return. Defaults to 100 when a time range is present. Values above 100 are silently clamped to 100. Without a time range, this parameter is ignored — the endpoint always returns the single latest price.

        pagination_key : typing.Optional[str]
            Base64-encoded cursor from a previous response to fetch the next page of results.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CryptoPricesResponse
            Crypto price data

        Examples
        --------
        import asyncio

        from predictorsdk import AsyncPredictorSDK

        client = AsyncPredictorSDK(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.get_binance_crypto_prices(
                currency="btcusdt",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_binance_crypto_prices(
            currency=currency,
            start_time=start_time,
            end_time=end_time,
            limit=limit,
            pagination_key=pagination_key,
            request_options=request_options,
        )
        return _response.data

    async def get_polymarket_wallet(
        self,
        *,
        address: typing.Optional[str] = None,
        username: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PolymarketWalletResponse:
        """
        Returns the public profile (image and display name) for a Polymarket wallet. Accepts either a wallet `address` (proxy or signer EOA) or a Polymarket `username`. Exactly one of the two must be supplied — passing both returns `400`.

        When `address` is the underlying signer EOA, the endpoint resolves it to the deterministic proxy address and returns the proxy's profile, with `signer` echoing the input.

        When `username` is supplied, the endpoint resolves it to the wallet via Polymarket's profile search. Match is case-insensitive and exact: a query of `Theo` resolves the user literally named `theo` but does not resolve `theo46` or `Theo47`. A leading `@` is accepted (and stripped) as a convenience for callers used to Twitter-style handles. `signer` is always `null` on the username path. Profiles that don't exist (or only match fuzzily) return `404`.

        Parameters
        ----------
        address : typing.Optional[str]
            Wallet address to look up. May be a Polymarket proxy address or the underlying signer EOA — the endpoint resolves either form. Must match `^0x[a-fA-F0-9]{40}$`. Mixed-case input is accepted and lowercased in the response. Mutually exclusive with `username`; exactly one of the two is required.

        username : typing.Optional[str]
            Polymarket display name to look up. Match is case-insensitive and exact against the user's stored `name` (so `Car`, `car`, and `CAR` all resolve, but `Theo` does not match `Theo47`). A leading `@` is accepted and stripped before the lookup. Mutually exclusive with `address`; exactly one of the two is required. Example: `Car`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PolymarketWalletResponse
            Public profile for the wallet

        Examples
        --------
        import asyncio

        from predictorsdk import AsyncPredictorSDK

        client = AsyncPredictorSDK(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.get_polymarket_wallet(
                address="0x7c3db723f1d4d8cb9c550095203b686cb11e5c6b",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_polymarket_wallet(
            address=address, username=username, request_options=request_options
        )
        return _response.data

    async def list_polymarket_wallet_positions(
        self,
        *,
        address: typing.Optional[str] = None,
        username: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PolymarketPositionsResponse:
        """
        Returns the current Polymarket positions for a wallet. Accepts either a wallet `address` (proxy address only — see note below) or a Polymarket `username`. Exactly one of the two must be supplied — passing both returns `400`.

        v1 surfaces a minimal field set so the endpoint scaffolding can be verified end-to-end: `condition_id` (which market), `outcome` (which side), and `shares` (how much). Title/slug, avg/current price, PnL (`cash_pnl`, `realized_pnl`), `redeemable`/`mergeable` flags, and event metadata will be added in follow-ups.

        `total` in the pagination block is always `0` because the upstream Data API does not return a total count; rely on `has_more` + `next_cursor` to paginate.

        **EOA inputs are not auto-resolved on this endpoint.** Unlike `/v1/polymarket/wallet`, this endpoint does not perform the EOA→proxy CREATE2 resolution. Callers with a signer EOA should call `/v1/polymarket/wallet` first to resolve the proxy, then pass the returned `address`. Passing an EOA directly will return an empty `data` array.

        Parameters
        ----------
        address : typing.Optional[str]
            Polymarket proxy wallet address. Must match `^0x[a-fA-F0-9]{40}$`. Mixed-case input is accepted and lowercased in the response. Mutually exclusive with `username`; exactly one of the two is required.

        username : typing.Optional[str]
            Polymarket display name to resolve to a proxy wallet. Match is case-insensitive and exact against the user's stored `name`. A leading `@` is accepted and stripped. Mutually exclusive with `address`.

        limit : typing.Optional[int]
            Number of items per page. Defaults to 50.

        cursor : typing.Optional[str]
            Opaque cursor from a previous response's `pagination.next_cursor`. Bound to the resolved wallet address — replaying a cursor against a different identifier returns `400`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PolymarketPositionsResponse
            Wallet positions

        Examples
        --------
        import asyncio

        from predictorsdk import AsyncPredictorSDK

        client = AsyncPredictorSDK(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.list_polymarket_wallet_positions(
                address="0x7c3db723f1d4d8cb9c550095203b686cb11e5c6b",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_polymarket_wallet_positions(
            address=address, username=username, limit=limit, cursor=cursor, request_options=request_options
        )
        return _response.data

    async def get_event(
        self,
        event_id: str,
        *,
        platform: typing.Optional[GetEventRequestPlatform] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EventResponse:
        """
        Returns a single event and the markets nested under it on the identified platform. The `event_id` is the platform's native identifier — a Kalshi `event_ticker`, a Polymarket event slug, an SX Bet `eventId`, or a Predict market identifier. The `platform` is inferred from the ID format when unambiguous (`KX…` → Kalshi, `L\\d+` → SX Bet). Numeric IDs and kebab-case slugs are shared shape between Polymarket and Predict; if `?platform=` is omitted in that case, the service probes Polymarket first and falls back to Predict when Polymarket returns 404. Pass `?platform=` explicitly to skip the probe.

        Response is minimal in v0: each market is returned with its platform-native `market_id` and a human-readable `title`. Pricing, volume, status, and timestamps are intentionally deferred — they'll be added as additive fields to `EventMarket` in a later release. The endpoint mirrors the `/v1/markets` rollout pattern (titles first, fields later).

        **Kalshi sibling fanout.** A single Kalshi sports game lives across multiple event tickers that share a game suffix — e.g. `KXMLBGAME-26MAY221840CLEPHI` holds the moneyline, `KXMLBF5TOTAL-26MAY221840CLEPHI` holds the totals, and so on. When the supplied event_ticker belongs to a sport in the sibling registry (MLB, NBA, NFL, NHL, WNBA today), this endpoint fans out across known sibling series in parallel and merges their markets into one response. Siblings that don't exist for a particular game silently drop. Siblings that error are reported under `fanout.siblings_missing`; the primary event still returns 200 in that case. Only the primary fetch failing produces a 4xx/5xx — partial fanouts never fail the request.

        **Polymarket** events already nest the moneyline plus all spread/totals/game-level prop markets under a single event slug, so no fanout is performed. **SX Bet** fixtures similarly bundle game lines per `eventId`. **Predict** currently treats `event_id` as a market identifier and wraps the single market as a 1-element event response, since the upstream `event` concept on Predict is closer to a category than to a multi-market container.

        Parameters
        ----------
        event_id : str
            Platform-native event identifier. Examples per platform: Kalshi event ticker (`KXMLBGAME-26MAY221840CLEPHI`), Polymarket event slug (`mlb-cle-phi-2026-05-22`), SX Bet event id (`L10073358`), Predict market id (`110629`).

        platform : typing.Optional[GetEventRequestPlatform]
            Optional platform override. When omitted, inferred from the `event_id` format: `KX…` → Kalshi, `L\\d+` → SX Bet. Numeric IDs and kebab-case slugs are shared shape between Polymarket and Predict; in that case the service probes Polymarket first and falls back to Predict on 404. Pass `platform` explicitly to skip the probe.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EventResponse
            Event with nested markets

        Examples
        --------
        import asyncio

        from predictorsdk import AsyncPredictorSDK

        client = AsyncPredictorSDK(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.get_event(
                event_id="KXMLBGAME-26MAY221840CLEPHI",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_event(event_id, platform=platform, request_options=request_options)
        return _response.data


def _get_base_url(*, base_url: typing.Optional[str] = None, environment: PredictorSDKEnvironment) -> str:
    if base_url is not None:
        return base_url
    elif environment is not None:
        return environment.value
    else:
        raise Exception("Please pass in either base_url or environment to construct the client")
