# This file was auto-generated by Fern from our API Definition.

import typing

import httpx
from .core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .core.logging import LogConfig, Logger
from .core.request_options import RequestOptions
from .environment import PredictorSdkApiEnvironment
from .raw_client import AsyncRawPredictorSdkApi, RawPredictorSdkApi
from .types.sports_matching_response import SportsMatchingResponse


class PredictorSdkApi:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : PredictorSdkApiEnvironment
        The environment to use for requests from the client. from .environment import PredictorSdkApiEnvironment



        Defaults to PredictorSdkApiEnvironment.PRODUCTION



    token : typing.Union[str, typing.Callable[[], str]]
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.Client]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    Examples
    --------
    from predictorsdk import PredictorSdkApi

    client = PredictorSdkApi(
        token="YOUR_TOKEN",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: PredictorSdkApiEnvironment = PredictorSdkApiEnvironment.PRODUCTION,
        token: typing.Union[str, typing.Callable[[], str]],
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.Client] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        )
        self._client_wrapper = SyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            token=token,
            headers=headers,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.Client(timeout=_defaulted_timeout, follow_redirects=follow_redirects)
            if follow_redirects is not None
            else httpx.Client(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
            logging=logging,
        )
        self._raw_client = RawPredictorSdkApi(client_wrapper=self._client_wrapper)

    @property
    def with_raw_response(self) -> RawPredictorSdkApi:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPredictorSdkApi
        """
        return self._raw_client

    def get_sports_matching_markets(
        self,
        *,
        kalshi_event_ticker: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        polymarket_market_slug: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        predict_market_id: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        sxbet_market_id: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SportsMatchingResponse:
        """
        Find cross-platform market matches for sports events. Provide a Kalshi event ticker or Polymarket market slug to look up the equivalent market on other platforms. When called without parameters, returns all currently matched sports markets.

        Parameters
        ----------
        kalshi_event_ticker : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Kalshi event ticker(s) to find matching markets for (e.g. `KXNFLGAME-25AUG16ARIDEN`). Provide the parameter multiple times for multiple tickers. Only one filter type may be used per request.

        polymarket_market_slug : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Polymarket market slug(s) to find matching markets for (e.g. `nfl-ari-den-2025-08-16`). Provide the parameter multiple times for multiple slugs. Only one filter type may be used per request.

        predict_market_id : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Predict market ID(s) to find matching markets for (e.g. `110629`). Provide the parameter multiple times for multiple IDs. Only one filter type may be used per request.

        sxbet_market_id : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            SX Bet market ID(s) to find matching markets for (e.g. `0x4c000abdbf197ef32ecdf15561b1d636f1e5b02629f466678757fd83e2ec3599`). Provide the parameter multiple times for multiple IDs. Only one filter type may be used per request.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SportsMatchingResponse
            Matching markets keyed by identifier

        Examples
        --------
        from predictorsdk import PredictorSdkApi

        client = PredictorSdkApi(
            token="YOUR_TOKEN",
        )
        client.get_sports_matching_markets()
        """
        _response = self._raw_client.get_sports_matching_markets(
            kalshi_event_ticker=kalshi_event_ticker,
            polymarket_market_slug=polymarket_market_slug,
            predict_market_id=predict_market_id,
            sxbet_market_id=sxbet_market_id,
            request_options=request_options,
        )
        return _response.data


class AsyncPredictorSdkApi:
    """
    Use this class to access the different functions within the SDK. You can instantiate any number of clients with different configuration that will propagate to these functions.

    Parameters
    ----------
    base_url : typing.Optional[str]
        The base url to use for requests from the client.

    environment : PredictorSdkApiEnvironment
        The environment to use for requests from the client. from .environment import PredictorSdkApiEnvironment



        Defaults to PredictorSdkApiEnvironment.PRODUCTION



    token : typing.Union[str, typing.Callable[[], str]]
    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    async_token : typing.Optional[typing.Callable[[], typing.Awaitable[str]]]
        An async callable that returns a bearer token. Use this when token acquisition involves async I/O (e.g., refreshing tokens via an async HTTP client). When provided, this is used instead of the synchronous token for async requests.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the timeout is 60 seconds, unless a custom httpx client is used, in which case this default is not enforced.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.AsyncClient]
        The httpx client to use for making requests, a preconfigured client is used by default, however this is useful should you want to pass in any custom httpx configuration.

    logging : typing.Optional[typing.Union[LogConfig, Logger]]
        Configure logging for the SDK. Accepts a LogConfig dict with 'level' (debug/info/warn/error), 'logger' (custom logger implementation), and 'silent' (boolean, defaults to True) fields. You can also pass a pre-configured Logger instance.

    Examples
    --------
    from predictorsdk import AsyncPredictorSdkApi

    client = AsyncPredictorSdkApi(
        token="YOUR_TOKEN",
    )
    """

    def __init__(
        self,
        *,
        base_url: typing.Optional[str] = None,
        environment: PredictorSdkApiEnvironment = PredictorSdkApiEnvironment.PRODUCTION,
        token: typing.Union[str, typing.Callable[[], str]],
        headers: typing.Optional[typing.Dict[str, str]] = None,
        async_token: typing.Optional[typing.Callable[[], typing.Awaitable[str]]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.AsyncClient] = None,
        logging: typing.Optional[typing.Union[LogConfig, Logger]] = None,
    ):
        _defaulted_timeout = (
            timeout if timeout is not None else 60 if httpx_client is None else httpx_client.timeout.read
        )
        self._client_wrapper = AsyncClientWrapper(
            base_url=_get_base_url(base_url=base_url, environment=environment),
            token=token,
            headers=headers,
            async_token=async_token,
            httpx_client=httpx_client
            if httpx_client is not None
            else httpx.AsyncClient(timeout=_defaulted_timeout, follow_redirects=follow_redirects)
            if follow_redirects is not None
            else httpx.AsyncClient(timeout=_defaulted_timeout),
            timeout=_defaulted_timeout,
            logging=logging,
        )
        self._raw_client = AsyncRawPredictorSdkApi(client_wrapper=self._client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPredictorSdkApi:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPredictorSdkApi
        """
        return self._raw_client

    async def get_sports_matching_markets(
        self,
        *,
        kalshi_event_ticker: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        polymarket_market_slug: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        predict_market_id: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        sxbet_market_id: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SportsMatchingResponse:
        """
        Find cross-platform market matches for sports events. Provide a Kalshi event ticker or Polymarket market slug to look up the equivalent market on other platforms. When called without parameters, returns all currently matched sports markets.

        Parameters
        ----------
        kalshi_event_ticker : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Kalshi event ticker(s) to find matching markets for (e.g. `KXNFLGAME-25AUG16ARIDEN`). Provide the parameter multiple times for multiple tickers. Only one filter type may be used per request.

        polymarket_market_slug : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Polymarket market slug(s) to find matching markets for (e.g. `nfl-ari-den-2025-08-16`). Provide the parameter multiple times for multiple slugs. Only one filter type may be used per request.

        predict_market_id : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Predict market ID(s) to find matching markets for (e.g. `110629`). Provide the parameter multiple times for multiple IDs. Only one filter type may be used per request.

        sxbet_market_id : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            SX Bet market ID(s) to find matching markets for (e.g. `0x4c000abdbf197ef32ecdf15561b1d636f1e5b02629f466678757fd83e2ec3599`). Provide the parameter multiple times for multiple IDs. Only one filter type may be used per request.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SportsMatchingResponse
            Matching markets keyed by identifier

        Examples
        --------
        import asyncio

        from predictorsdk import AsyncPredictorSdkApi

        client = AsyncPredictorSdkApi(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.get_sports_matching_markets()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_sports_matching_markets(
            kalshi_event_ticker=kalshi_event_ticker,
            polymarket_market_slug=polymarket_market_slug,
            predict_market_id=predict_market_id,
            sxbet_market_id=sxbet_market_id,
            request_options=request_options,
        )
        return _response.data


def _get_base_url(*, base_url: typing.Optional[str] = None, environment: PredictorSdkApiEnvironment) -> str:
    if base_url is not None:
        return base_url
    elif environment is not None:
        return environment.value
    else:
        raise Exception("Please pass in either base_url or environment to construct the client")
