# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .ambiguous_identifier_error import AmbiguousIdentifierError
    from .canonical_sports_event import CanonicalSportsEvent
    from .canonical_sports_outcome import CanonicalSportsOutcome
    from .canonical_sports_participant import CanonicalSportsParticipant
    from .canonical_sports_rules import CanonicalSportsRules
    from .canonical_sports_source_market import CanonicalSportsSourceMarket
    from .canonical_sports_source_market_provider import CanonicalSportsSourceMarketProvider
    from .canonical_sports_source_outcome import CanonicalSportsSourceOutcome
    from .canonical_sports_subject import CanonicalSportsSubject
    from .canonical_sports_submarket import CanonicalSportsSubmarket
    from .canonical_sports_submarket_settlement_equivalence import CanonicalSportsSubmarketSettlementEquivalence
    from .categories_response import CategoriesResponse
    from .category_info import CategoryInfo
    from .crypto_price_item import CryptoPriceItem
    from .crypto_prices_response import CryptoPricesResponse
    from .error_response import ErrorResponse
    from .event_fanout import EventFanout
    from .event_market import EventMarket
    from .event_response import EventResponse
    from .event_response_platform import EventResponsePlatform
    from .get_event_request_platform import GetEventRequestPlatform
    from .get_market_request_platform import GetMarketRequestPlatform
    from .get_markets_request_provider import GetMarketsRequestProvider
    from .get_sports_matching_markets_request_player_prop_match import GetSportsMatchingMarketsRequestPlayerPropMatch
    from .market_category import MarketCategory
    from .market_detail_fee_leg import MarketDetailFeeLeg
    from .market_detail_fee_leg_model import MarketDetailFeeLegModel
    from .market_detail_fee_rounding import MarketDetailFeeRounding
    from .market_detail_fee_rounding_direction import MarketDetailFeeRoundingDirection
    from .market_detail_outcome import MarketDetailOutcome
    from .market_detail_pricing import MarketDetailPricing
    from .market_detail_pricing_as_of_kind import MarketDetailPricingAsOfKind
    from .market_detail_pricing_availability import MarketDetailPricingAvailability
    from .market_detail_pricing_scale import MarketDetailPricingScale
    from .market_detail_pricing_source import MarketDetailPricingSource
    from .market_detail_response import MarketDetailResponse
    from .market_detail_response_provider import MarketDetailResponseProvider
    from .market_detail_response_status import MarketDetailResponseStatus
    from .market_detail_scheduled_fee_change import MarketDetailScheduledFeeChange
    from .market_detail_trading_fees import MarketDetailTradingFees
    from .market_detail_trading_fees_availability import MarketDetailTradingFeesAvailability
    from .market_detail_trading_fees_charge_basis import MarketDetailTradingFeesChargeBasis
    from .market_detail_trading_fees_source import MarketDetailTradingFeesSource
    from .markets_list_response import MarketsListResponse
    from .markets_snapshot import MarketsSnapshot
    from .pagination_block import PaginationBlock
    from .payment_required_error_action import PaymentRequiredErrorAction
    from .payment_required_error_body import PaymentRequiredErrorBody
    from .plan import Plan
    from .plans_response import PlansResponse
    from .player_prop_rule_comparison import PlayerPropRuleComparison
    from .player_prop_rule_comparison_comparison import PlayerPropRuleComparisonComparison
    from .player_prop_rule_comparison_rule import PlayerPropRuleComparisonRule
    from .player_prop_rule_source_value import PlayerPropRuleSourceValue
    from .polymarket_position import PolymarketPosition
    from .polymarket_positions_response import PolymarketPositionsResponse
    from .polymarket_wallet_response import PolymarketWalletResponse
    from .sports_matching_response import SportsMatchingResponse
    from .sports_matching_snapshot import SportsMatchingSnapshot
    from .unified_market import UnifiedMarket
    from .unified_market_provider import UnifiedMarketProvider
_dynamic_imports: typing.Dict[str, str] = {
    "AmbiguousIdentifierError": ".ambiguous_identifier_error",
    "CanonicalSportsEvent": ".canonical_sports_event",
    "CanonicalSportsOutcome": ".canonical_sports_outcome",
    "CanonicalSportsParticipant": ".canonical_sports_participant",
    "CanonicalSportsRules": ".canonical_sports_rules",
    "CanonicalSportsSourceMarket": ".canonical_sports_source_market",
    "CanonicalSportsSourceMarketProvider": ".canonical_sports_source_market_provider",
    "CanonicalSportsSourceOutcome": ".canonical_sports_source_outcome",
    "CanonicalSportsSubject": ".canonical_sports_subject",
    "CanonicalSportsSubmarket": ".canonical_sports_submarket",
    "CanonicalSportsSubmarketSettlementEquivalence": ".canonical_sports_submarket_settlement_equivalence",
    "CategoriesResponse": ".categories_response",
    "CategoryInfo": ".category_info",
    "CryptoPriceItem": ".crypto_price_item",
    "CryptoPricesResponse": ".crypto_prices_response",
    "ErrorResponse": ".error_response",
    "EventFanout": ".event_fanout",
    "EventMarket": ".event_market",
    "EventResponse": ".event_response",
    "EventResponsePlatform": ".event_response_platform",
    "GetEventRequestPlatform": ".get_event_request_platform",
    "GetMarketRequestPlatform": ".get_market_request_platform",
    "GetMarketsRequestProvider": ".get_markets_request_provider",
    "GetSportsMatchingMarketsRequestPlayerPropMatch": ".get_sports_matching_markets_request_player_prop_match",
    "MarketCategory": ".market_category",
    "MarketDetailFeeLeg": ".market_detail_fee_leg",
    "MarketDetailFeeLegModel": ".market_detail_fee_leg_model",
    "MarketDetailFeeRounding": ".market_detail_fee_rounding",
    "MarketDetailFeeRoundingDirection": ".market_detail_fee_rounding_direction",
    "MarketDetailOutcome": ".market_detail_outcome",
    "MarketDetailPricing": ".market_detail_pricing",
    "MarketDetailPricingAsOfKind": ".market_detail_pricing_as_of_kind",
    "MarketDetailPricingAvailability": ".market_detail_pricing_availability",
    "MarketDetailPricingScale": ".market_detail_pricing_scale",
    "MarketDetailPricingSource": ".market_detail_pricing_source",
    "MarketDetailResponse": ".market_detail_response",
    "MarketDetailResponseProvider": ".market_detail_response_provider",
    "MarketDetailResponseStatus": ".market_detail_response_status",
    "MarketDetailScheduledFeeChange": ".market_detail_scheduled_fee_change",
    "MarketDetailTradingFees": ".market_detail_trading_fees",
    "MarketDetailTradingFeesAvailability": ".market_detail_trading_fees_availability",
    "MarketDetailTradingFeesChargeBasis": ".market_detail_trading_fees_charge_basis",
    "MarketDetailTradingFeesSource": ".market_detail_trading_fees_source",
    "MarketsListResponse": ".markets_list_response",
    "MarketsSnapshot": ".markets_snapshot",
    "PaginationBlock": ".pagination_block",
    "PaymentRequiredErrorAction": ".payment_required_error_action",
    "PaymentRequiredErrorBody": ".payment_required_error_body",
    "Plan": ".plan",
    "PlansResponse": ".plans_response",
    "PlayerPropRuleComparison": ".player_prop_rule_comparison",
    "PlayerPropRuleComparisonComparison": ".player_prop_rule_comparison_comparison",
    "PlayerPropRuleComparisonRule": ".player_prop_rule_comparison_rule",
    "PlayerPropRuleSourceValue": ".player_prop_rule_source_value",
    "PolymarketPosition": ".polymarket_position",
    "PolymarketPositionsResponse": ".polymarket_positions_response",
    "PolymarketWalletResponse": ".polymarket_wallet_response",
    "SportsMatchingResponse": ".sports_matching_response",
    "SportsMatchingSnapshot": ".sports_matching_snapshot",
    "UnifiedMarket": ".unified_market",
    "UnifiedMarketProvider": ".unified_market_provider",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AmbiguousIdentifierError",
    "CanonicalSportsEvent",
    "CanonicalSportsOutcome",
    "CanonicalSportsParticipant",
    "CanonicalSportsRules",
    "CanonicalSportsSourceMarket",
    "CanonicalSportsSourceMarketProvider",
    "CanonicalSportsSourceOutcome",
    "CanonicalSportsSubject",
    "CanonicalSportsSubmarket",
    "CanonicalSportsSubmarketSettlementEquivalence",
    "CategoriesResponse",
    "CategoryInfo",
    "CryptoPriceItem",
    "CryptoPricesResponse",
    "ErrorResponse",
    "EventFanout",
    "EventMarket",
    "EventResponse",
    "EventResponsePlatform",
    "GetEventRequestPlatform",
    "GetMarketRequestPlatform",
    "GetMarketsRequestProvider",
    "GetSportsMatchingMarketsRequestPlayerPropMatch",
    "MarketCategory",
    "MarketDetailFeeLeg",
    "MarketDetailFeeLegModel",
    "MarketDetailFeeRounding",
    "MarketDetailFeeRoundingDirection",
    "MarketDetailOutcome",
    "MarketDetailPricing",
    "MarketDetailPricingAsOfKind",
    "MarketDetailPricingAvailability",
    "MarketDetailPricingScale",
    "MarketDetailPricingSource",
    "MarketDetailResponse",
    "MarketDetailResponseProvider",
    "MarketDetailResponseStatus",
    "MarketDetailScheduledFeeChange",
    "MarketDetailTradingFees",
    "MarketDetailTradingFeesAvailability",
    "MarketDetailTradingFeesChargeBasis",
    "MarketDetailTradingFeesSource",
    "MarketsListResponse",
    "MarketsSnapshot",
    "PaginationBlock",
    "PaymentRequiredErrorAction",
    "PaymentRequiredErrorBody",
    "Plan",
    "PlansResponse",
    "PlayerPropRuleComparison",
    "PlayerPropRuleComparisonComparison",
    "PlayerPropRuleComparisonRule",
    "PlayerPropRuleSourceValue",
    "PolymarketPosition",
    "PolymarketPositionsResponse",
    "PolymarketWalletResponse",
    "SportsMatchingResponse",
    "SportsMatchingSnapshot",
    "UnifiedMarket",
    "UnifiedMarketProvider",
]
