# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .crypto_price_item import CryptoPriceItem
    from .crypto_prices_response import CryptoPricesResponse
    from .error_response import ErrorResponse
    from .platform_market import PlatformMarket
    from .platform_market_platform import PlatformMarketPlatform
    from .sports_matching_response import SportsMatchingResponse
_dynamic_imports: typing.Dict[str, str] = {
    "CryptoPriceItem": ".crypto_price_item",
    "CryptoPricesResponse": ".crypto_prices_response",
    "ErrorResponse": ".error_response",
    "PlatformMarket": ".platform_market",
    "PlatformMarketPlatform": ".platform_market_platform",
    "SportsMatchingResponse": ".sports_matching_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CryptoPriceItem",
    "CryptoPricesResponse",
    "ErrorResponse",
    "PlatformMarket",
    "PlatformMarketPlatform",
    "SportsMatchingResponse",
]
