# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CanonicalSportsRules(UniversalBaseModel):
    settlement: typing.Optional[str] = pydantic.Field(default=None)
    """
    Overtime treatment the submarket's key carries: `incl_ot` (the default) or `reg` on a full-game total or team total, and `incl_ot` on a second-half or fourth-quarter spread, total or team total whose venues' own rules count overtime. A half or quarter means regulation play, so a regulation line publishes no `rules`. Kept for compatibility; the `overtime` row of the submarket's `rule_comparisons` (sent with `include_rules=true`) is each venue's own statement of the same rule and never contradicts it.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
