# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .canonical_sports_outcome import CanonicalSportsOutcome
from .canonical_sports_rules import CanonicalSportsRules
from .canonical_sports_source_market import CanonicalSportsSourceMarket
from .canonical_sports_subject import CanonicalSportsSubject
from .canonical_sports_submarket_settlement_equivalence import CanonicalSportsSubmarketSettlementEquivalence
from .player_prop_rule_comparison import PlayerPropRuleComparison


class CanonicalSportsSubmarket(UniversalBaseModel):
    settlement_equivalence: typing.Optional[CanonicalSportsSubmarketSettlementEquivalence] = pydantic.Field(
        default=None
    )
    """
    Whether the venues in this submarket settle it the same way, across the rules in `rule_comparisons`. Always present on moneyline, spread, total, team total and player prop submarkets, whether or not `include_rules` asked for the rows behind it. `equivalent` means every rule is known for every venue and agrees; `different` means at least one known difference, even if other rules are unknown; `unverified` means no difference was found but a rule is unknown for at least one venue, so equivalence has not been established. A player prop is `equivalent` only with a complete reviewed profile for every source contract. A game line is compared on three rules, `tie`, `overtime` and `push`, and the comparison never changes which venues are paired: it is the evidence a consumer needs to decide whether a pairing is a hedge. In practice a game line differs on a tie only in a league that can end a game level, which today is the NFL (about 0.3% of games).
    """

    rule_comparisons: typing.Optional[typing.List[PlayerPropRuleComparison]] = pydantic.Field(default=None)
    """
    The rule matrix behind `settlement_equivalence`: one row per rule, each listing every source market's value. A moneyline, spread, total or team total carries three rows, `tie`, `overtime` and `push`, only when the request sent `include_rules=true`; without it they are omitted and the verdict stands alone. A player prop always carries its nine. Filter rows with `comparison=different` for known differences and `comparison=unverified` for gaps. Row-level agreement is not a complete contract review. Source values reference individual native market IDs, not venue-wide defaults. Evidence describes captured source clauses; additional unreviewed terms can apply. No prices or payout estimates.
    """

    key: str = pydantic.Field()
    """
    Stable canonical submarket key within the event. A second-half or fourth-quarter spread, total or team total whose venues' own rules count overtime ends its detail with `:incl_ot` (`spread|half:2|spread:jax:incl_ot|2.5`); the same line on a venue whose rules exclude overtime has the key without the token, so the two are never one submarket. A team total's key names its team and states its overtime rule the way a game total's does (`team_total|full|team_total:phi:incl_ot|24.5`), so two teams' lines never share a key.
    """

    market_type: str = pydantic.Field()
    """
    What the submarket is: `moneyline`, `spread`, `total` (the game's total points), `team_total` (one team's own points, such as the Eagles over 24.5; its `subject` is the team), or `player_prop`. Not an enum: a value a client does not know yet is a new kind of market, never a different shape of an old one, and a client reads it as text. A team total is matched for the NFL, on Kalshi and Polymarket.
    """

    segment: str = pydantic.Field()
    """
    `full`, `half:1`, `half:2`, or `quarter:1` to `quarter:4`. A half or quarter means regulation play, except a second half or fourth quarter whose venues count overtime, which says so in `rules.settlement` (`incl_ot`), in its `key` and in its `display_name`.
    """

    display_name: str = pydantic.Field()
    """
    Human-readable label. A second-half or fourth-quarter line that counts overtime ends with ` (incl. OT)`, because a bare `2H` reads as regulation play. A team total names its team: `Philadelphia Eagles Total 24.5`, `1H Philadelphia Eagles Total 13.5`.
    """

    metric: str = pydantic.Field()
    """
    What the submarket measures: `winner`, `spread`, `total`, a player prop's statistic, or, for a team total, the team's own score in its sport's unit (`points` for the NFL).
    """

    line: typing.Optional[float] = pydantic.Field(default=None)
    """
    Unsigned threshold for totals, team totals and player props; signed handicap for spreads. Omitted for moneyline markets.
    """

    subject: typing.Optional[CanonicalSportsSubject] = pydantic.Field(default=None)
    """
    Participant or player whose line is represented. Present for subject-owned markets such as spreads, team totals and player props; omitted for event-owned moneylines and totals.
    """

    rules: typing.Optional[CanonicalSportsRules] = None
    outcomes: typing.List[CanonicalSportsOutcome]
    source_markets: typing.List[CanonicalSportsSourceMarket]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
