# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .canonical_sports_participant import CanonicalSportsParticipant
from .canonical_sports_submarket import CanonicalSportsSubmarket


class CanonicalSportsEvent(UniversalBaseModel):
    event_id: str = pydantic.Field()
    """
    Stable canonical event key.
    """

    sport: typing.Optional[str] = pydantic.Field(default=None)
    """
    Canonical sport slug. `basketball`, `hockey`, or `baseball` today.
    """

    league: typing.Optional[str] = pydantic.Field(default=None)
    """
    Canonical league slug. Cross-platform matching covers `nba`, `wnba`, `nhl`, and `mlb` today. The value is the first segment of `event_id`, so `nba-okc-sas-2026-10-20` is an NBA game. Treat this as an open set — leagues are added without a breaking change.
    """

    title: str
    participants: typing.Optional[typing.List[CanonicalSportsParticipant]] = None
    submarkets: typing.List[CanonicalSportsSubmarket]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
