# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CanonicalSportsSubject(UniversalBaseModel):
    type: str = pydantic.Field()
    """
    Canonical subject kind, such as `participant` or `player`.
    """

    key: str = pydantic.Field()
    """
    Stable subject key within the canonical sports namespace.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable subject name.
    """

    team: typing.Optional[str] = pydantic.Field(default=None)
    """
    Canonical team key when the subject is a player.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
