# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CanonicalSportsSourceOutcome(UniversalBaseModel):
    canonical_outcome_key: str = pydantic.Field()
    """
    Canonical outcome this source-native selection represents.
    """

    label: typing.Optional[str] = None
    outcome_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Exact provider-native outcome/token identifier when available. SX Bet exposes one market hash and two named positions rather than separate outcome tokens, so its source-local selection reference is `<market_hash>:1` or `<market_hash>:2`. This field is never a universal cross-provider outcome ID.
    """

    side: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional source-native side such as `yes` or `no`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
