# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .canonical_sports_source_market_provider import CanonicalSportsSourceMarketProvider
from .canonical_sports_source_outcome import CanonicalSportsSourceOutcome


class CanonicalSportsSourceMarket(UniversalBaseModel):
    provider: CanonicalSportsSourceMarketProvider
    market_id: str = pydantic.Field()
    """
    Exact provider-native market identifier.
    """

    market_name: typing.Optional[str] = None
    market_slug: typing.Optional[str] = None
    outcomes: typing.List[CanonicalSportsSourceOutcome]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
