# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .canonical_sports_source_market_provider import CanonicalSportsSourceMarketProvider
from .canonical_sports_source_outcome import CanonicalSportsSourceOutcome


class CanonicalSportsSourceMarket(UniversalBaseModel):
    provider: CanonicalSportsSourceMarketProvider
    market_id: str = pydantic.Field()
    """
    Exact provider-native market identifier. It resolves on `GET /v1/markets/{market_id}`, either as-is or prefixed with this row's `provider` in the composite form `{provider}:{market_id}`.
    
    One provider can contribute MORE THAN ONE entry to the same submarket, because a provider is free to model one canonical market as several native ones. Kalshi does exactly that for a game moneyline: it lists one binary market per team ("Arizona wins", "San Francisco wins"), so a Kalshi moneyline row appears twice, once per team ticker, each with its own `yes`/`no` outcomes. Group by `provider` if you need one row per venue; do not assume the list has at most one entry per provider.
    """

    market_name: typing.Optional[str] = None
    market_slug: typing.Optional[str] = None
    outcomes: typing.List[CanonicalSportsSourceOutcome]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
