# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .canonical_sports_outcome import CanonicalSportsOutcome
from .canonical_sports_rules import CanonicalSportsRules
from .canonical_sports_source_market import CanonicalSportsSourceMarket
from .canonical_sports_subject import CanonicalSportsSubject


class CanonicalSportsSubmarket(UniversalBaseModel):
    key: str = pydantic.Field()
    """
    Stable canonical submarket key within the event.
    """

    market_type: str
    segment: str
    display_name: typing.Optional[str] = None
    metric: typing.Optional[str] = None
    line: typing.Optional[float] = pydantic.Field(default=None)
    """
    Unsigned threshold for totals and player props; signed handicap for spreads. Omitted for moneyline markets.
    """

    subject: typing.Optional[CanonicalSportsSubject] = pydantic.Field(default=None)
    """
    Participant or player whose line is represented. Present for subject-owned markets such as spreads and player props; omitted for event-owned moneylines and totals.
    """

    rules: typing.Optional[CanonicalSportsRules] = None
    outcomes: typing.List[CanonicalSportsOutcome]
    source_markets: typing.List[CanonicalSportsSourceMarket]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
