# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .canonical_sports_outcome import CanonicalSportsOutcome
from .canonical_sports_rules import CanonicalSportsRules
from .canonical_sports_source_market import CanonicalSportsSourceMarket
from .canonical_sports_subject import CanonicalSportsSubject
from .canonical_sports_submarket_settlement_equivalence import CanonicalSportsSubmarketSettlementEquivalence
from .player_prop_rule_comparison import PlayerPropRuleComparison


class CanonicalSportsSubmarket(UniversalBaseModel):
    settlement_equivalence: typing.Optional[CanonicalSportsSubmarketSettlementEquivalence] = pydantic.Field(
        default=None
    )
    """
    Player props only. `equivalent` requires a complete reviewed profile for every source contract; `different` means at least one known payout-rule difference, even if other rules are unknown; `unverified` means equivalence has not been established and no known difference was found. Absence on game lines makes no claim about their full settlement equivalence.
    """

    rule_comparisons: typing.Optional[typing.List[PlayerPropRuleComparison]] = pydantic.Field(default=None)
    """
    Player props only. A deterministic matrix covering all nine settlement dimensions. Filter rows with `comparison=different` for known differences and `comparison=unverified` for gaps. Row-level agreement is not a complete contract review. Source values reference individual native market IDs, not venue-wide defaults. Evidence describes captured source clauses; additional unreviewed terms can apply. No prices or payout estimates.
    """

    key: str = pydantic.Field()
    """
    Stable canonical submarket key within the event.
    """

    market_type: str
    segment: str
    display_name: typing.Optional[str] = None
    metric: typing.Optional[str] = None
    line: typing.Optional[float] = pydantic.Field(default=None)
    """
    Unsigned threshold for totals and player props; signed handicap for spreads. Omitted for moneyline markets.
    """

    subject: typing.Optional[CanonicalSportsSubject] = pydantic.Field(default=None)
    """
    Participant or player whose line is represented. Present for subject-owned markets such as spreads and player props; omitted for event-owned moneylines and totals.
    """

    rules: typing.Optional[CanonicalSportsRules] = None
    outcomes: typing.List[CanonicalSportsOutcome]
    source_markets: typing.List[CanonicalSportsSourceMarket]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
