# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .canonical_sports_participant import CanonicalSportsParticipant
from .canonical_sports_submarket import CanonicalSportsSubmarket


class CanonicalSportsEvent(UniversalBaseModel):
    event_id: str = pydantic.Field()
    """
    Stable canonical event key.
    """

    sport: typing.Optional[str] = None
    league: typing.Optional[str] = None
    title: str
    participants: typing.Optional[typing.List[CanonicalSportsParticipant]] = None
    submarkets: typing.List[CanonicalSportsSubmarket]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
