# This file was auto-generated by Fern from our API Definition.

import typing

CanonicalSportsSubmarketSettlementEquivalence = typing.Union[
    typing.Literal["equivalent", "different", "unverified"], typing.Any
]
