# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .crypto_price_item import CryptoPriceItem


class CryptoPricesResponse(UniversalBaseModel):
    prices: typing.List[CryptoPriceItem]
    pagination_key: typing.Optional[str] = pydantic.Field(default=None)
    """
    Base64-encoded cursor for fetching the next page. Absent when there are no more results.
    """

    total: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of prices in this response page. Omitted on empty responses for unknown symbols.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
