# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CryptoPriceItem(UniversalBaseModel):
    symbol: str = pydantic.Field()
    """
    Trading pair in lowercase (e.g. `btcusdt`).
    """

    value: float = pydantic.Field()
    """
    Close price for the 1-second interval.
    """

    timestamp: int = pydantic.Field()
    """
    Unix timestamp in milliseconds for the start of the 1-second interval.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
