# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .crypto_price_item import CryptoPriceItem
from .pagination_block import PaginationBlock


class CryptoPricesResponse(UniversalBaseModel):
    data: typing.List[CryptoPriceItem] = pydantic.Field()
    """
    One page of prices, newest first, one per second. A single item when no time range was sent; `[]` for an unknown symbol.
    """

    pagination: PaginationBlock = pydantic.Field()
    """
    Pagination metadata for the current page. `total` is always `null` on this route, and `next_cursor` goes back as `cursor`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
