# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .event_fanout import EventFanout
from .event_market import EventMarket
from .event_response_platform import EventResponsePlatform


class EventResponse(UniversalBaseModel):
    event_id: str = pydantic.Field()
    """
    Echo of the platform-native event identifier supplied in the request path.
    """

    platform: EventResponsePlatform = pydantic.Field()
    """
    The platform the event_id was resolved against, either inferred from the ID format or supplied via `?platform=`.
    """

    title: str = pydantic.Field()
    """
    Human-readable event title from the platform.
    """

    markets: typing.List[EventMarket] = pydantic.Field()
    """
    Markets nested under this event. Order is platform-native for the primary event, followed by markets from fanout siblings (Kalshi sports) in registry order.
    """

    fanout: typing.Optional[EventFanout] = pydantic.Field(default=None)
    """
    Present when the response was assembled from multiple upstream events (Kalshi sports sibling fanout). Lists which sibling event tickers were attempted, which contributed markets, and which failed or didn't exist. Absent for non-Kalshi platforms and for Kalshi events whose series is not in the sibling registry.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
