# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class EventFanout(UniversalBaseModel):
    siblings_attempted: typing.List[str] = pydantic.Field()
    """
    Sibling event tickers the server attempted to fetch alongside the primary event. Determined by the Kalshi sibling registry for the primary event's series.
    """

    siblings_returned: typing.List[str] = pydantic.Field()
    """
    Sibling event tickers that returned successfully and contributed markets to the merged response.
    """

    siblings_missing: typing.List[str] = pydantic.Field()
    """
    Sibling event tickers that did not exist upstream (404) or errored. The primary event still returned 200 — these are reported for observability, not as request failures.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
