# This file was auto-generated by Fern from our API Definition.

import typing

GetMarketsRequestProvider = typing.Union[
    typing.Literal["kalshi", "polymarket", "predict", "sxbet", "hyperliquid", "alpha-arcade"], typing.Any
]
