# This file was auto-generated by Fern from our API Definition.

import typing

GetEventRequestProvider = typing.Union[
    typing.Literal[
        "kalshi", "polymarket", "predict", "sxbet", "hyperliquid", "alpha-arcade", "prophetx", "limitless", "pred"
    ],
    typing.Any,
]
