# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .market_detail_fee_leg import MarketDetailFeeLeg
from .market_detail_scheduled_fee_change import MarketDetailScheduledFeeChange
from .market_detail_trading_fees_availability import MarketDetailTradingFeesAvailability
from .market_detail_trading_fees_charge_basis import MarketDetailTradingFeesChargeBasis
from .market_detail_trading_fees_source import MarketDetailTradingFeesSource


class MarketDetailTradingFees(UniversalBaseModel):
    """
    The trading fee the PREDICTION MARKET charges on a trade in this market — the venue's own published parameters, normalized. This has nothing to do with PredictorSDK's subscription pricing.

    Always present on the response. Every published model across the six platforms is a per-share fee times the traded share count, and only the price term differs, so `taker.model` plus its parameters expresses each venue exactly rather than approximating any of them. Compute the fee yourself:

    `fee = shares × f(price)`, then apply `rounding`, where `f` is

    - `quadratic`: `rate × (price × (1 − price)) ^ exponent`
    - `min_price`: `rate × min(price, 1 − price)`
    - `notional`: `rate × price`
    - `none`: `0`

    The effective rate on notional — what you actually compare across venues — is `f(price) / price`. For `quadratic` at `exponent: 1` that reduces to `rate × (1 − price)`, which is why no single basis-point figure can express any of these venues: at `rate: 0.07` the effective cost runs from 693 bps at a price of 0.01 down to 7 bps at 0.99.

    `availability` and the legs are on separate axes on purpose: availability says what is KNOWN, the legs say what is CHARGED. A fee-free market is `availability: published` with `model: "none"` and `rate: 0` — an asserted zero, distinguishable from `unpublished` (the venue publishes nothing) and from `account_specific` (rates exist but are per-account).

    OUT OF SCOPE and therefore not modeled as fields, though each is real and moves the number: rebates (Polymarket's maker-rebate and taker-rebate programs), per-account discounts (Predict's 10% invite discount), volume/staking tiers (Hyperliquid), and third-party pass-through (Kalshi FCM customers, Polymarket builder fees). The parameters here are the venue's PUBLISHED base for this market; a specific account may pay less.
    """

    availability: MarketDetailTradingFeesAvailability = pydantic.Field()
    """
    `published` — the full parameter set for this market is known. `partial` — fees may be charged here but a parameter is missing or uninterpretable upstream; the legs carry what is known and null the rest, never a guess. It also covers the case where the parameters in force are known but the venue's pending-change list was unreadable, so an omitted `scheduled_change` means "unknown" rather than "none". `account_specific` — rates exist but are set per trading account and require your own venue credentials (SX Bet's `GET /user/fees-v3`, Hyperliquid's `POST /info {"type":"userFees"}`). `unpublished` — the venue publishes no fee model for this market at all. `unavailable` — our own bounded parameter fetch failed or timed out; identity and pricing are still served. Same contract as `pricing.availability`.
    """

    observed_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When PredictorSDK READ these parameter values — an observation timestamp, not an upstream stamp.
    
    Named `observed_at` rather than `as_of` deliberately: `pricing.as_of` is the provider record's own last-update time, which is a different thing, and reusing the name for a differently-defined timestamp would bake that confusion into a second field. Null when nothing is read at request time (`source: venue_schedule`) or when nothing could be read (`availability: unavailable`).
    """

    source: MarketDetailTradingFeesSource = pydantic.Field()
    """
    Where the parameters came from, so a latency-sensitive consumer knows which platforms cost extra hops. `market_record` — embedded in the same market record the identity fetch already returned (Polymarket `feeSchedule`, Predict `feeRateBps`, AlphaArcade `feeBasePercent`); zero extra fetches. `series_record` — the parameters live on parent records and cost up to three small, TTL-cached hops (Kalshi: the event record for its series ticker and any fee override in force, the series for the base `fee_type`/`fee_multiplier` that override supersedes, then the event's pending fee changes for `scheduled_change`). `venue_schedule` — the venue exposes no per-market parameter and the answer comes from its published schedule (SX Bet, Hyperliquid).
    """

    charge_basis: typing.Optional[MarketDetailTradingFeesChargeBasis] = pydantic.Field(default=None)
    """
    What the fee is assessed on. `fill` — assessed when the order fills, from the traded share count and the fill price. `settlement_profit` — assessed at settlement, on profit (total return − stake), and only on a position that WON; a loss or a void is never charged.
    
    Read this before comparing rates across venues. SX Bet charges on winning profit at settlement, so its fee is an expected-value haircut rather than an entry cost — a consumer that models it as a percentage of notional is wrong about the shape before it is wrong about the rate. The reported basis is the one that applies to trading: SX Bet's four payout fees. Its separate `refundFee` is charged at fill time on the capital-efficiency refund rather than on profit, and is out of scope here along with its rates.
    """

    taker: typing.Optional[MarketDetailFeeLeg] = None
    maker: typing.Optional[MarketDetailFeeLeg] = None
    scheduled_change: typing.Optional[MarketDetailScheduledFeeChange] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
