# This file was auto-generated by Fern from our API Definition.

import typing

MarketDetailPricingAsOfKind = typing.Union[
    typing.Literal["quote", "record_refresh", "record_static", "unknown"], typing.Any
]
