# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .pagination_block import PaginationBlock
from .unified_market import UnifiedMarket


class MarketsListResponse(UniversalBaseModel):
    data: typing.List[UnifiedMarket] = pydantic.Field()
    """
    Array of markets for the current page.
    """

    pagination: PaginationBlock = pydantic.Field()
    """
    Pagination metadata for the current page.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
