# This file was auto-generated by Fern from our API Definition.

import typing

MarketDetailTradingFeesSource = typing.Union[
    typing.Literal["market_record", "series_record", "venue_schedule"], typing.Any
]
