# This file was auto-generated by Fern from our API Definition.

import typing

MarketCategory = typing.Union[
    typing.Literal[
        "sports",
        "politics",
        "crypto",
        "finance",
        "economics",
        "weather",
        "culture",
        "technology",
        "entertainment",
        "other",
        "unknown",
    ],
    typing.Any,
]
