# This file was auto-generated by Fern from our API Definition.

import typing

MarketDetailTradingFeesAvailability = typing.Union[
    typing.Literal["published", "partial", "account_specific", "unpublished", "unavailable"], typing.Any
]
