# This file was auto-generated by Fern from our API Definition.

import typing

MarketDetailPricingAvailability = typing.Union[
    typing.Literal["live", "indicative", "partial", "no_quotes", "unavailable"], typing.Any
]
