# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PaginationBlock(UniversalBaseModel):
    limit: int = pydantic.Field()
    """
    Page size this page was served with. It echoes the first-page `limit` query value; for cursor-native passthrough endpoints, a supplied cursor's page size takes precedence on later pages.
    """

    total: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total matching items across all pages, when the route can count them. `null` when it cannot: `GET /v1/polymarket/wallet/positions` and `GET /v1/crypto-prices/binance` read upstreams that give no count, and neither route walks a result to find one. `0` therefore only ever means an empty result. Rely on `has_more` and `next_cursor` to paginate, whatever `total` says.
    """

    has_more: bool = pydantic.Field()
    """
    Whether additional pages exist beyond this one.
    """

    next_cursor: typing.Optional[str] = pydantic.Field(default=None)
    """
    Opaque cursor for fetching the next page. Pass back via the `cursor` query parameter. Omitted when `has_more` is `false`. Clients must preserve the same filter set when re-using a cursor — mismatches return `400`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
