# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .payment_required_error_action import PaymentRequiredErrorAction


class PaymentRequiredErrorBody(UniversalBaseModel):
    """
    Error body returned with HTTP 402. The `action` discriminator lets clients route to the correct recovery flow: `upgrade_plan` means the caller is on a lower tier than the endpoint requires, or the Free monthly allowance is exhausted; `resolve_payment` means the caller had a paid subscription that entered a payment-recovery state (past_due/unpaid/paused/incomplete) and the backend has already downgraded them to Free — the fix is in the billing portal, not a new purchase. `required_tier` / `current_tier` are always populated; `included_requests_per_month` and `current_period_requests` are only set when a Free caller hits the monthly allowance.
    """

    error: str
    message: typing.Optional[str] = pydantic.Field(default=None)
    """
    Additional detail about the error.
    """

    status_code: int
    action: PaymentRequiredErrorAction = pydantic.Field()
    """
    Recommended client action for this 402.
    """

    required_tier: str = pydantic.Field()
    """
    Billing tier that would satisfy the gate (e.g. `starter`, `pro`, `business`, `enterprise`).
    """

    current_tier: str = pydantic.Field()
    """
    Billing tier currently associated with the caller.
    """

    included_requests_per_month: typing.Optional[int] = pydantic.Field(default=None)
    """
    Monthly Free-tier allowance. Present only when the 402 is caused by the Free cap.
    """

    current_period_requests: typing.Optional[int] = pydantic.Field(default=None)
    """
    Requests the Free caller has made in the current calendar month. Present only when the 402 is caused by the Free cap.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
