# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class Plan(UniversalBaseModel):
    """
    Public plan metadata. Stripe price IDs and legacy provisioning IDs are intentionally absent.
    """

    key: str = pydantic.Field()
    """
    Stable public plan key.
    """

    name: str
    billing_tier: str = pydantic.Field()
    """
    Runtime entitlement tier; empty for a manually provisioned contact-sales plan.
    """

    trial_days: int
    tagline: str
    monthly_price_cents: int = pydantic.Field()
    """
    Monthly display price in US cents; zero for free or contact-sales plans.
    """

    included_requests_per_month: int
    overage_cents_per1k: typing_extensions.Annotated[
        int, FieldMetadata(alias="overage_cents_per_1k"), pydantic.Field(alias="overage_cents_per_1k")
    ]
    rate_limit_per_min: int
    max_keys: int
    features: typing.List[str]
    cta_label: str
    highlighted: bool
    contact_sales: bool

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
