# This file was auto-generated by Fern from our API Definition.

import typing

PlayerPropRuleComparisonRule = typing.Union[
    typing.Literal[
        "non_participation",
        "overtime",
        "stat_definition",
        "threshold",
        "stat_corrections",
        "postponement",
        "cancellation",
        "interruption",
        "resolution_source",
    ],
    typing.Any,
]
