# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .player_prop_rule_comparison_comparison import PlayerPropRuleComparisonComparison
from .player_prop_rule_comparison_rule import PlayerPropRuleComparisonRule
from .player_prop_rule_source_value import PlayerPropRuleSourceValue


class PlayerPropRuleComparison(UniversalBaseModel):
    rule: PlayerPropRuleComparisonRule
    label: str = pydantic.Field()
    """
    Human-readable name of the rule dimension.
    """

    comparison: PlayerPropRuleComparisonComparison = pydantic.Field()
    """
    Known differences take precedence over unknown source values.
    """

    source_values: typing.List[PlayerPropRuleSourceValue]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
