# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PlayerPropRuleSourceValue(UniversalBaseModel):
    provider: str = pydantic.Field()
    """
    Lowercase provider slug matching a source_markets entry.
    """

    market_id: str = pydantic.Field()
    """
    Exact native market ID matching a source_markets entry.
    """

    value: str = pydantic.Field()
    """
    Machine-readable observed rule value, or `unknown`. Values are extensible; clients must tolerate unfamiliar values and read description. Never interpret unknown as no restriction.
    """

    description: str = pydantic.Field()
    """
    Plain-language meaning, including relevant qualifications.
    """

    evidence_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Source contract containing the observed clause; omitted for unknown rules.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
