# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .pagination_block import PaginationBlock
from .polymarket_position import PolymarketPosition


class PolymarketPositionsResponse(UniversalBaseModel):
    address: str = pydantic.Field()
    """
    Resolved Polymarket proxy wallet (lowercased).
    """

    data: typing.List[PolymarketPosition]
    pagination: PaginationBlock

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
