# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PolymarketPosition(UniversalBaseModel):
    condition_id: str = pydantic.Field()
    """
    Polymarket condition ID (`0x`-prefixed hex).
    """

    outcome: str = pydantic.Field()
    """
    Outcome label held in this position (`Yes`/`No` for binary markets).
    """

    shares: float = pydantic.Field()
    """
    Number of outcome shares held.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
