# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PolymarketWalletResponse(UniversalBaseModel):
    address: str = pydantic.Field()
    """
    Polymarket proxy address (lowercased) the profile is keyed on. When the input was a signer EOA, this is the resolved proxy.
    """

    signer: typing.Optional[str] = pydantic.Field(default=None)
    """
    Original signer EOA from the request, when the input was an EOA that resolved to a different proxy. `null` when the input was already a proxy address (no resolution needed) or when no populated profile could be found for the resolved proxy.
    """

    profile_image: typing.Optional[str] = pydantic.Field(default=None)
    """
    URL of the wallet's profile image, or `null` if unset.
    """

    display_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    User-chosen display name when set; otherwise the auto-generated pseudonym Polymarket assigns. `null` only when both are missing.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
