# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .canonical_sports_event import CanonicalSportsEvent
from .pagination_block import PaginationBlock
from .sports_matching_snapshot import SportsMatchingSnapshot


class SportsMatchingResponse(UniversalBaseModel):
    canonical_events: typing.Dict[str, CanonicalSportsEvent] = pydantic.Field()
    """
    Matched events. Keyed by canonical event ID in list mode, and in lookup mode by each `event_id` or `source_id` exactly as sent (surrounding whitespace trimmed), so an identifier that matched nothing is simply absent. Present on every response, as `{}` when nothing matched.
    """

    pagination: typing.Optional[PaginationBlock] = pydantic.Field(default=None)
    """
    Pagination metadata for the current page. Present in list mode (no `event_id` or `source_id`). Absent in lookup mode, since the response is bounded by the identifiers requested.
    """

    snapshot: SportsMatchingSnapshot = pydantic.Field()
    """
    Freshness of the matching snapshot this response was read from. Present in list and lookup mode alike. Describes the DATA; `pagination` describes the page.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
