# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .canonical_sports_event import CanonicalSportsEvent
from .sports_matching_lookup_result import SportsMatchingLookupResult
from .sports_matching_snapshot import SportsMatchingSnapshot


class SportsMatchingLookupResponse(UniversalBaseModel):
    data: typing.List[CanonicalSportsEvent] = pydantic.Field()
    """
    The matched events the identifiers found, soonest scheduled start first, each once however many identifiers found it. Present on every response, as `[]` when nothing matched.
    """

    lookups: typing.Dict[str, SportsMatchingLookupResult] = pydantic.Field()
    """
    Every `event_id` and `source_id` sent, under its spelling as sent (whitespace around the provider and ID trimmed), with the canonical events in `data` that hold it. An identifier that found nothing is listed with no events.
    """

    snapshot: SportsMatchingSnapshot = pydantic.Field()
    """
    Freshness of the matching snapshot this response was read from. Present even when no identifier matched, which is when it matters most.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
