# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .canonical_sports_event import CanonicalSportsEvent
from .pagination_block import PaginationBlock
from .sports_matching_snapshot import SportsMatchingSnapshot


class SportsMatchingListResponse(UniversalBaseModel):
    data: typing.List[CanonicalSportsEvent] = pydantic.Field()
    """
    One page of matched events, soonest scheduled start first, each once. Present on every response, as `[]` when nothing matched.
    """

    pagination: PaginationBlock = pydantic.Field()
    """
    Pagination metadata for the current page. `total` counts the events that match the request's filters, not every matched event.
    """

    snapshot: SportsMatchingSnapshot = pydantic.Field()
    """
    Freshness of the matching snapshot this response was read from. Describes the DATA; `pagination` describes the page.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
