# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .canonical_sports_event import CanonicalSportsEvent
from .pagination_block import PaginationBlock
from .sports_matching_lookup import SportsMatchingLookup
from .sports_matching_snapshot import SportsMatchingSnapshot


class SportsMatchingResponse(UniversalBaseModel):
    data: typing.List[CanonicalSportsEvent] = pydantic.Field()
    """
    Matched events, soonest scheduled start first, each once however many lookup identifiers found it. Present on every response, as `[]` when nothing matched.
    """

    lookups: typing.Optional[typing.Dict[str, SportsMatchingLookup]] = pydantic.Field(default=None)
    """
    Lookup mode only: every `event_id` and `source_id` sent, under its spelling as sent (whitespace around the provider and ID trimmed), with the canonical events in `data` that hold it. An identifier that found nothing is listed with no events. Absent in list mode.
    """

    pagination: typing.Optional[PaginationBlock] = pydantic.Field(default=None)
    """
    Pagination metadata for the current page. Present in list mode (no `event_id` or `source_id`). Absent in lookup mode, since the response is bounded by the identifiers requested.
    """

    snapshot: SportsMatchingSnapshot = pydantic.Field()
    """
    Freshness of the matching snapshot this response was read from. Present in list and lookup mode alike. Describes the DATA; `pagination` describes the page.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
