# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .unified_market_provider import UnifiedMarketProvider


class UnifiedMarket(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Composite market identifier in the format `{provider}:{provider_id}` (e.g. `kalshi:KXNBAGAME-26MAR06INDLAL-LAL`).
    """

    provider: UnifiedMarketProvider = pydantic.Field()
    """
    Prediction market provider.
    """

    title: str = pydantic.Field()
    """
    Human-readable market title/question.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
